# ansible-playbook -i '[[ip]],' -u ddm devvm.yaml -kK
--- 
- hosts: all
  become: yes
  tasks:
  - name: install base packages
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - tmux
      - vim
      - sudo
      - fail2ban
      - apache2-utils
      - man
      - htop
  - name: install docker dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: adding existing user "{{ ansible_user }}" to group docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
